### ISSUE TITLE
R05: Improve email received on moderated content

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As a moderator (process-admin), I would like to receive an e-mail with a link directly to the backend for the individual proposal when a message arrives, instead of a link to the frontend as is currently the case.

**Mock up**

**Does this issue could impact on users private data?**

**Acceptance criteria**
- [x] Improve email received on moderated content

**Technical specifications**
https://github.com/openpoke/decidim/issues/21

**Implementation**
- [x] https://github.com/openpoke/decidim/pull/31

**Testing**
Steps to reproduce: https://letterbox.dev.pokecode.net/
1. As a user, I report one content
2. As an admin, I receive an email with link to hide/unhide 
![imatge](https://user-images.githubusercontent.com/40388743/193054925-1d4987d0-2327-4ac1-bc31-c0fa4148d3cf.png)

**Additional context**
Metadecidim proposal: https://meta.decidim.org/processes/roadmap/f/122/proposals/17115

**Comment by Naadjjaa** [comment]
@paarals This issue is a little missunderstood. We did not mean the messages for reported content but for new proposals arriving. Original text: As a moderator (process-admin), I would like to receive an e-mail with a **link directly to the backend** for the individual proposal when a message **(=proposal)** arrives, instead of a link to the frontend as is currently the case.

**Comment by paarals** [comment]
closed by sprint 3
